version: '3'
services:
  web:
    build: .
    command: gunicorn -k gevent -w 1 -b 0.0.0.0:8000 run:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
  worker:
    build: .
    command: celery -A flask_chat.celery_worker.celery worker --pool=gevent --concurrency=50 -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:latest
